name: PHP CI

on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main ]

env:
  TARGET_SERVER_IP: "10.0.0.x"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.2', '7.3' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer
        run: |
          php --version
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      - name: Insatll phplint
        run: |
          composer require overtrue/phplint --dev -vvv
          ./vendor/bin/phplint --version

      - name: Run php lint
        run: |
          ./vendor/bin/phplint --exclude=vendor ./app -vv

      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "always"
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build tar archive
        run: |
          tar cvf zip.tar.gz --exclude tests/ ./
          ls -lhi zip.tar.gz

      - name: Deploy target
        run: |
          echo "$TARGET_SERVER_IP へ deployする処理を書く"
