name: PHP CI

on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_on:
        description: 'デプロイを行う際は手動で実行させる'
        required: true
        default: false


env:
  # CI時にPHPのバージョンを切り替える用に変数としておく
  PHP_VERSION: "7.3"
  # デプロイ先のサーバのIPを定義しておく
  TARGET_SERVER_IP: "10.0.0.x"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["${PHP_VERSION}"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer
        run: |
          php --version
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      - name: Insatll phplint
        run: |
          composer require overtrue/phplint --dev -vvv
          ./vendor/bin/phplint --version

      # ユーザアプリケーションのlintを実行する
      - name: Run php lint
        run: |
          ./vendor/bin/phplint --exclude=vendor ./app -vv

      # lint失敗時はslackへ通知する
      - name: Slack Notification (not success)
        uses: lazy-actions/slatify@master
        if: "! success()"
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }} # slack通知用のwebhookurlは表示されると困るのでsecretsに定義しておく
          token: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    # lintが通ってない場合はリリースを行わない
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # ビルドでは無いけどtarに固める
      - name: Build tar archive
        run: |
          tar cvf zip.tar.gz --exclude tests/ ./
          ls -lhi zip.tar.gz

      - name: Deploy target
        run: |
          echo "$TARGET_SERVER_IP へ deployする処理を書く"
        if: ${{ github.event.inputs.deploy_on == true }}
